<button class="btn btn-success" onclick="location.href='/admin/ufs/save'">Novo uf</button>

<table class="table">
    <thead>
    <tr>
        <td>Id</td><td>Descrição</td>
    </tr>
    </thead>
    <tbody>
        <?php foreach($uf as $uf) {
        ?>
            <tr>
                <td>
                    <?php echo $uf->getId(); ?>
                </td>
                <td>
                    <?php echo $uf->getDescUf(); ?>
                </td>
                <td>
                    <a href="/admin/uf/save/id/<?php echo $uf->getId(); ?>">Editar</a>
                </td>
                <td>
                    <a href="/admin/uf/delete/id/<?php echo $uf->getId(); ?>">Excluir</a>
                </td>
            </tr>
        <?php }
        ?>
    </tbody>

</table>
