<button class="btn btn-success" onclick="location.href='/admin/ceps/save'">Novo cep</button>

<table class="table">
    <thead>
    <tr>
        <td>Id</td><td>Descrição</td>
    </tr>
    </thead>
    <tbody>
        <?php foreach($cep as $cep) {
        ?>
            <tr>
                <td>
                    <?php echo $cep->getId(); ?>
                </td>
                <td>
                    <?php echo $cep->getDescCep(); ?>
                </td>
                <td>
                    <a href="/admin/cep/save/id/<?php echo $cep->getId(); ?>">Editar</a>
                </td>
                <td>
                    <a href="/admin/cep/delete/id/<?php echo $cep->getId(); ?>">Excluir</a>
                </td>
            </tr>
        <?php }
        ?>
    </tbody>

</table>
