<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Projeto')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('usuarios') ?>"><?php echo $this->translate('Home') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active" ><a href="/admin/usuarios">Usuários</a></li>
			            <li class=""><a href="/admin/interesses">Interesses</a></li>
			            <li class=""><a href="/admin/sexos">Sexos</a></li>
			            <li class=""><a href="/admin/login/logout">Sair</a></li>
                    </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="alert-info" style="padding: 20px; margin-bottom: 30px;" >
                Olá <?php echo $this->session()->offsetGet('user')->getNome();
                ?>
                <br>
                Você está na seguinte url: <?php echo $this->currentUrl(); ?>
            </div>
            <!-- Msg Success -->

            <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                <div class="alert-success">
                    <?php
                    foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
                        echo $msg;
                    }
                    ?>

                </div>
            <?php } ?>
            <!-- Msg Error -->

            <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                <div class="alert-danger">
                    <?php
                    foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                        echo $msg;
                    }
                    ?>
                </div>
            <?php } ?>

            <!-- Msg Warning -->

            <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                <div class="alert-warning">
                    <?php
                    foreach ($this->flashMessenger()->getInfoMessages() as $msg) {
                        echo $msg;
                    }
                    ?>
                </div>
            <?php } ?>
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; Minha app</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
